title: "Lifecycle Mastery: Power Platform ALM for Agents"
description: "A hands-on workshop demonstrating modern ALM for Power Platform with a focus on Managed Environments, solution-aware pipelines, and agent-ready governance patterns."

# Theme
theme: jekyll-theme-cayman

# Basic settings
markdown: kramdown
highlighter: rouge

# Plugins (only the essential ones that GitHub Pages supports)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - SECURITY.md
  - .gitignore